version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: mateuszkozak97/lab9_chmura
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=chmura
      - MYSQL_USER=mkozak
      - MYSQL_PASS=haslo123
      - MYSQL_DB_NAME=baza
    volumes:
      - ./www/:/var/www/html/
    depends_on:
      - Cloud2020-88732
    networks:
      - Bridge-Zadanie-1
  mysql:
    image: mysql:5.7
    networks:
      Bridge-Zadanie-1:
        ipv4_address: 10.0.10.3
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mkozak
      - MYSQL_PASSWORD=haslo123 
      - MYSQL_DATABASE=baza
    container_name: Cloud2020-88727
networks:
  frontend:
  backend: